name: CI/CD Production Pipeline

# Déclencheur : Un push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  deploy-to-local-vm:
    # CRUCIAL : On dit à GitHub d'utiliser ton runner local, pas ses serveurs cloud
    runs-on: self-hosted

    steps:
      - name: Execute Local Deploy Script
        run: |
          cd ~/flask_oracle_project
          ./deploy.sh
